[package]
name = "practice-rust"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
mdbook = "0.4.35"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html